### ISSUE TITLE
Syntax Highlighting Broken in Nova 4.1

### ISSUE THREAD

**Issue by mattpilott** [laosb/SvelteNova#1]
Hello,

Good work on putting this extension together *super* helpful!

Since updating to Nova 4.1 it seems the syntax highlighting has become broken, I have tried the reinstalling and hitting the reload extension button but no luck.

Let me know if you need anything more from me

**Comment by kevmodrome** [comment]
Also seeing this. It highlights the script and style tags but nothing else. Tried looking around in the extension to figure it out but I am quite lost 😬

**Comment by benjfriedrich** [comment]
Just here to 1-up this issue. I like Nova, and am missing my Svelte syntax highlighting! Thanks for all the work already done on this...hope the updates didn't break anything too badly

**Comment by jonahgoldwastaken** [comment]
I found out that when you add a space to the end of line with `<style>` or `<script>`, it highlights the code inside those blocks. The issue probably lies with the regular expressions used to detect these opening tags. I've been peeking at them for the last hour but cannot find the solution to the issue as I've only dabbled with JS regular expressions before and the PERL ones seem to be a whole other beast.

Does anyone know where you can find the included syntax files for Nova? Maybe the solution lies in the updated versions of those, as the Svelte syntax file is just a modified copy of the HTML syntax one, as specified [here](https://github.com/laosb/SvelteNova/blob/f55a5ca26af51eee09245fbfce9b8b77530afe98/SvelteNova.novaextension/Syntaxes/Svelte.xml#L3).

**Comment by pierreminik** [comment]
Do you guys mind trying out PR #2? It should fix the issue of missing syntax highlighting for scripts.

**Comment by pierreminik** [comment]
Didn't notice `style` syntax also was broken. Fixing that.
Also just noticed that both `script` and `style` no longer auto closes when typing `</` so trying to fix that too.

**Comment by pierreminik** [comment]
Styling should be syntax highlighted now but I couldn't find a reference for the auto-closing of `script` and `style`. The Vue extension seems to have that bug too and I couldn't find working code in the examples by Panic.

**Comment by jonahgoldwastaken** [comment]
Excellent work @pierreminik, it works like a charm for me! 😄

**Comment by Suges** [comment]
Really fine work @pierreminik, saved my life! ❤️

I don't understand LSPs or Nova extensions at all. I wish we could find some way to make the Svelte warnings show up in-line like they do in VS Code. I never want to go back to VS Code! 😩

**Comment by laosb** [comment]
Now this should be fixed in 0.1.5 release. I also updated `svelte-language-server` to date in this release. Thanks @pierreminik  for fixing syntax highlight and everyone for participating in this issue!

Please reopen if this persists.
