### ISSUE TITLE
Tree-Sitter

### ISSUE THREAD

**Issue by BryanSchuetz** [laosb/SvelteNova#10]
Any chance a tree-sitter version of this extension is being worked on?

**Comment by laosb** [comment]
I've been working on it since the first Nova 10 beta, albeit I have my daily job to do (which also partly uses Svelte so I do have some reason to work a little on this during the day) so there's not too much of progress, yet.

I'll keep you updated.

**Comment by laosb** [comment]
There's already some foundation for tree-sitter support on `main` branch so check that out if you're interested in that, or better if you can offer help.

**Comment by laosb** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/2545261/199775344-bf7f5fab-fcd3-4c95-8ae0-d0ef83d7292f.png">

Dare I say it's getting pretty good!

I will say that's enough for its debut, putting together a release.

**Comment by laosb** [comment]
v0.2.0 is released with `tree-sitter` support!
