### ISSUE TITLE
TypeScript definition not recognized in Svelte script tag

### ISSUE THREAD

**Issue by acarr** [laosb/SvelteNova#3]
Working on a project where I have a local `*.d.ts` file with some defined types in it. Nova (with the TypeScrpt extension) is able to find the declaration file and provide IntelliSense in all *.ts files in the project. 

But using TypeScript within a Svelte component script tag does not recognize the types from the declaration file. This _may_ be a TypeScript extension issue but I think it's more likely an issue with the Svelte extension so starting here first.

Example project here: https://github.com/acarr/svelte-ts-nova-test

So given a declaration file like in `global.d.ts`...
```typescript
// global.d.ts
interface User {
  firstName: string;
  lastName: string;
  age?: number;
}
```

the types are recognized correctly in the `main.ts` file in the Svelte project.
```typescript
// main.ts
import App from './App.svelte';
let test:User = {
	firstName: "Aria",
	lastName: "Stark"
}
const app = new App({
	target: document.body,
	props: {
		user: test
	}
});
export default app;
```

And a screenshot of the same in Nova:
<img width="438" alt="CleanShot 2021-04-06 at 21 47 08@2x" src="https://user-images.githubusercontent.com/237203/113798690-abfafe00-9721-11eb-8748-b82811d96161.png">

But inside of a Svelte component, Nova does not recognize the `User` type.
```svelte
<!-- App.svelte -->
<script lang="ts">
	export let user: User;
</script>

<main>
	<h1>Hello {user.firstName} {user.lastName} {user.age}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
</main>

```

And a screenshot of the error in Nova:
<img width="408" alt="CleanShot 2021-04-06 at 21 48 30@2x" src="https://user-images.githubusercontent.com/237203/113798801-df3d8d00-9721-11eb-9b4c-d621ddf65172.png">

Any thoughts or direction on where the issue might be is appreciated!

**Comment by laosb** [comment]
I suspect it's a svelte-language-server problem. Can you confirm if this is fixed in v0.2.0 with SLS 0.14.37?
