### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mattpilott** [laosb/SvelteNova#4]
Since Nova 6.1 it seems sveltenova's node process is eating up cpu, disabling the svelte nova extension resolves the issue

Also this is happening without having any files or terminals open, so when nova is just idle

<img width="953" alt="Screenshot 2021-04-26 at 2 14 08 pm" src="https://user-images.githubusercontent.com/2401925/116089331-a480a200-a69a-11eb-9907-dfb9666c3afa.png">

**Comment by laosb** [comment]
I've been using Nova 6.1 with this extension to code a SvelteKit app and have no issue on this so far. Maybe related to https://github.com/sveltejs/language-tools/issues/965 ? Anyway we will need to wait for new releases of `language-server`.

**Comment by mattpilott** [comment]
Yeah it happens with no files open, which is odd

**Comment by maxime-pigeon** [comment]
Any update on this issue? I, too, am seeing high CPU usage. It seems that sveltejs/language-tools#965 was somewhat fixed by sveltejs/language-tools#967.

**Comment by laosb** [comment]
I see. Maybe we can try bumping to latest language server? Will do.

**Comment by maxime-pigeon** [comment]
@laosb Thank you for looking into it. 🙏 Will keep you posted once it's updated.

**Comment by laosb** [comment]
Just released 0.1.7 bumping to lang server 0.14.6. I'll leave this open for sometime to see if this is resolved. 😁

**Comment by maxime-pigeon** [comment]
Can't speak for @matt3224, but it looks like it solved the problem on my end. Thanks!

**Comment by laosb** [comment]
Great news! Let's leave this open longer to see.

**Comment by mattpilott** [comment]
I havent noticed any issue since the update 🤞 its fixed
