### ISSUE TITLE
JSDoc or @component documentation not being displayed

### ISSUE THREAD

**Issue by johngrasty** [laosb/SvelteNova#5]
Hi,

First off, thanks for the extension for such a new application! Second, I'm sorry that I am just reporting that issue and not helping fix it, but unfortanetly, it is a bit beyond my abilities at the moment. 😁 

I'm seeing a situation where my JSDoc comments or @component documentation is sometimes being displayed and sometimes not. I've not being able to find rhyme or reason yet for the discrepancy. Possibly related is that sometimes the "Jump to Definition" works and sometimes not. 

Any ideas on how to debug this?

**Comment by laosb** [comment]
Likely the language server crashed when it's not displayed.

**Comment by laosb** [comment]
Closing since there's no repro.
