### ISSUE TITLE
Autocompletion gets accepted via comma and period

### ISSUE THREAD

**Issue by gustavneustadt** [laosb/SvelteNova#9]
Seems like autocomplete suggestions get accepted via comma and period. 
Me personally drives this behaviour crazy because I cant write arrays without messing up – but there could've been reasons for this(?).

![Screen Recording 2022-07-11 at 08 43 15](https://user-images.githubusercontent.com/35671734/178366522-0ad8d229-f6df-4cf1-ad8b-361ff7783f52.gif)

Maybe an issue with the nova typescript extension.

**Comment by laosb** [comment]
I experience this too. Maybe even a problem with Nova itself, cuz I hit this in many file formats.

**Comment by gustavneustadt** [comment]
[Got an solution via Twitter.](https://twitter.com/politics_pod/status/1546672176086016005?s=46&t=2PXNdje2sLgm0JIqUlEepA) 

![C06DB464-E007-409E-96C3-9008274E2B35](https://user-images.githubusercontent.com/35671734/193068905-55dc4fa6-96e9-4674-a63f-d2152f9c0437.jpeg)
